# Generated by Django 5.2.16 on 2026-07-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrialItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=255, verbose_name="客户名称"),
                ),
                (
                    "project_manager",
                    models.CharField(max_length=100, verbose_name="项目负责人"),
                ),
                (
                    "project_site",
                    models.CharField(max_length=255, verbose_name="项目现场"),
                ),
                ("trial_start_date", models.DateField(verbose_name="试用时间（开始）")),
                (
                    "trial_period_days",
                    models.PositiveIntegerField(verbose_name="试用周期（天）"),
                ),
                (
                    "expiration_date",
                    models.DateField(blank=True, null=True, verbose_name="到期时间"),
                ),
                (
                    "trial_days",
                    models.PositiveIntegerField(default=0, verbose_name="已试用时间"),
                ),
                (
                    "over_due_status",
                    models.CharField(
                        choices=[
                            ("not_due", "未到期"),
                            ("due", "到期"),
                            ("over_due", "超期"),
                        ],
                        default="not_due",
                        max_length=20,
                        verbose_name="是否超期",
                    ),
                ),
                ("closed", models.BooleanField(default=False, verbose_name="是否完结")),
                (
                    "resell",
                    models.BooleanField(default=False, verbose_name="是否转销售"),
                ),
                (
                    "sales_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="销售金额",
                    ),
                ),
                (
                    "return_date",
                    models.DateField(blank=True, null=True, verbose_name="还回时间"),
                ),
                (
                    "days_after_return",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="归还后天数"
                    ),
                ),
                (
                    "product_model",
                    models.CharField(max_length=100, verbose_name="产品名称"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                ("sn", models.CharField(max_length=100, verbose_name="SN")),
                ("pn", models.CharField(max_length=100, verbose_name="PN")),
                ("shipping_info", models.TextField(verbose_name="收货信息")),
                (
                    "contract_no",
                    models.CharField(max_length=100, verbose_name="合同号"),
                ),
                (
                    "logistics_info",
                    models.CharField(max_length=255, verbose_name="物流信息"),
                ),
                (
                    "outbound_shipment_number",
                    models.CharField(max_length=100, verbose_name="出库单号"),
                ),
                (
                    "warehouse",
                    models.CharField(max_length=100, verbose_name="拿货仓库"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "试用项目",
                "verbose_name_plural": "试用项目表",
            },
        ),
    ]
