# Generated by Django 5.2.16 on 2026-07-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TrialItem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trialitem",
            name="quantity",
            field=models.CharField(max_length=20, verbose_name="数量"),
        ),
    ]
