# Generated by Django 5.2.16 on 2026-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TrialItem", "0002_alter_trialitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trialitem",
            name="return_date",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="还回时间"
            ),
        ),
        migrations.AlterField(
            model_name="trialitem",
            name="sales_amount",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="销售金额"
            ),
        ),
    ]
