# Generated by Django 5.2.16 on 2026-07-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TrialItem", "0003_alter_trialitem_return_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trialitem",
            name="trial_period_days",
            field=models.CharField(
                default="30", max_length=10, verbose_name="试用周期（天）"
            ),
        ),
    ]
