# Generated by Django 5.2.16 on 2026-07-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TrialItem", "0004_alter_trialitem_trial_period_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trialitem",
            name="trial_days",
            field=models.IntegerField(default=0, verbose_name="已试用时间"),
        ),
    ]
