# Generated by Django 5.2.16 on 2026-07-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TrialItem", "0005_alter_trialitem_trial_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trialitem",
            name="contract_no",
            field=models.CharField(blank=True, max_length=100, verbose_name="合同号"),
        ),
        migrations.AlterField(
            model_name="trialitem",
            name="logistics_info",
            field=models.CharField(blank=True, max_length=255, verbose_name="物流信息"),
        ),
        migrations.AlterField(
            model_name="trialitem",
            name="outbound_shipment_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="出库单号"),
        ),
        migrations.AlterField(
            model_name="trialitem",
            name="pn",
            field=models.CharField(blank=True, max_length=100, verbose_name="PN"),
        ),
        migrations.AlterField(
            model_name="trialitem",
            name="product_model",
            field=models.CharField(blank=True, max_length=100, verbose_name="产品名称"),
        ),
        migrations.AlterField(
            model_name="trialitem",
            name="project_site",
            field=models.CharField(blank=True, max_length=255, verbose_name="项目现场"),
        ),
        migrations.AlterField(
            model_name="trialitem",
            name="quantity",
            field=models.CharField(blank=True, max_length=20, verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="trialitem",
            name="shipping_info",
            field=models.TextField(blank=True, verbose_name="收货信息"),
        ),
        migrations.AlterField(
            model_name="trialitem",
            name="sn",
            field=models.CharField(blank=True, max_length=100, verbose_name="SN"),
        ),
        migrations.AlterField(
            model_name="trialitem",
            name="warehouse",
            field=models.CharField(blank=True, max_length=100, verbose_name="拿货仓库"),
        ),
    ]
