# Generated by Django 5.2.16 on 2026-07-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AfterSalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="用户名称"
                    ),
                ),
                (
                    "after_sales_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="售后类型"
                    ),
                ),
                ("no", models.CharField(blank=True, max_length=50, verbose_name="NO.")),
                (
                    "after_sales_no",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="售后编号",
                    ),
                ),
                (
                    "project_site",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="项目现场"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="是否解决"),
                ),
                (
                    "return_date",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="退货时间"
                    ),
                ),
                (
                    "product_name_model",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="货物品名及型号"
                    ),
                ),
                (
                    "original_ship_date",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="发货时间（原件）"
                    ),
                ),
                (
                    "out_of_warranty",
                    models.BooleanField(default=False, verbose_name="是否过保"),
                ),
                (
                    "sn",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="SN"
                    ),
                ),
                (
                    "pn",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="PN"
                    ),
                ),
                (
                    "return_reason_description",
                    models.TextField(blank=True, verbose_name="退货原因描述"),
                ),
                ("rca", models.TextField(blank=True, verbose_name="RCA")),
                (
                    "after_sales_cost",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="售后成本"
                    ),
                ),
                (
                    "charge_details",
                    models.TextField(blank=True, verbose_name="收费明细"),
                ),
                (
                    "ship_date",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="寄货时间"
                    ),
                ),
                (
                    "customer_return_required",
                    models.BooleanField(default=False, verbose_name="是否需客户寄回"),
                ),
                (
                    "shipped_item_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="寄货品名"
                    ),
                ),
                (
                    "r_sn",
                    models.CharField(blank=True, max_length=100, verbose_name="R_SN"),
                ),
                (
                    "r_pn",
                    models.CharField(blank=True, max_length=100, verbose_name="R_PN"),
                ),
                (
                    "equipment_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="设备编号"
                    ),
                ),
                (
                    "outbound_order_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="出库单号"
                    ),
                ),
                (
                    "shipping_info",
                    models.TextField(blank=True, verbose_name="寄货信息"),
                ),
                (
                    "tracking_no",
                    models.CharField(blank=True, max_length=100, verbose_name="运单号"),
                ),
                (
                    "source_warehouse",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="拿货仓库"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "售后记录",
                "verbose_name_plural": "售后记录",
                "ordering": ["-return_date"],
                "indexes": [
                    models.Index(
                        fields=["after_sales_no"], name="product_aft_after_s_340e67_idx"
                    ),
                    models.Index(fields=["sn"], name="product_aft_sn_0c9d38_idx"),
                    models.Index(fields=["pn"], name="product_aft_pn_6ec794_idx"),
                    models.Index(
                        fields=["return_date"], name="product_aft_return__df932e_idx"
                    ),
                    models.Index(
                        fields=["resolved"], name="product_aft_resolve_3fee17_idx"
                    ),
                ],
            },
        ),
    ]
